[build]
  command="ng build"
  publish="dist/angular-quickstart"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
path='/err'
function='badFunction'